sudo: enabled

language: elm

elm:
  - "0.19.0"

env:
  - PROTO_HOME=/usr/local/include
  
install:
  - curl -L https://github.com/google/protobuf/releases/download/v3.7.0/protoc-3.7.0-linux-x86_64.zip -o /tmp/protoc.zip
  - unzip /tmp/protoc.zip -d /tmp/protoc
  - sudo mv /tmp/protoc/bin/* /usr/local/bin/
  - sudo mv /tmp/protoc/include/* /usr/local/include/
  - npm install

script:
  - ./build.sh
  - protoc --plugin="protoc-gen-elm=index.js" --elm_out=tests tests/test.proto
  - elm-format --validate .
  - elm make --output=/dev/null tests/Protoc/Gen/Elm/Test.elm
  - git diff
  - git diff-index --quiet HEAD --
