{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Google.Protobuf.Descriptor exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 1.0.0
- `protoc` 3.14.0
- the following specification file: `google/protobuf/descriptor.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.1.0) version 1.1.0 or higher.


-}

import Bytes
import Maybe
import Protobuf.Decode
import Protobuf.Encode


{-| Decode a `GeneratedCodeInfo` from Bytes


-}
defaultGeneratedCodeInfo : GeneratedCodeInfo
defaultGeneratedCodeInfo =
    { annotation = [] }


{-| Decode a `GeneratedCodeInfo` from Bytes


-}
decodeGeneratedCodeInfo : Protobuf.Decode.Decoder GeneratedCodeInfo
decodeGeneratedCodeInfo =
    Protobuf.Decode.message
        defaultGeneratedCodeInfo
        [ Protobuf.Decode.repeated 1 decodeGeneratedCodeInfo_Annotation .annotation (\a r -> { r | annotation = a }) ]


{-| Encode a `GeneratedCodeInfo` to Bytes


-}
encodeGeneratedCodeInfo : GeneratedCodeInfo -> Protobuf.Encode.Encoder
encodeGeneratedCodeInfo value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.list encodeGeneratedCodeInfo_Annotation value.annotation ) ]


{-| `GeneratedCodeInfo` message


-}
type alias GeneratedCodeInfo =
    { annotation : List GeneratedCodeInfo_Annotation }


{-| Decode a `GeneratedCodeInfo_Annotation` from Bytes


-}
defaultGeneratedCodeInfo_Annotation : GeneratedCodeInfo_Annotation
defaultGeneratedCodeInfo_Annotation =
    { path = [], sourceFile = "", begin = 0, end = 0 }


{-| Decode a `GeneratedCodeInfo_Annotation` from Bytes


-}
decodeGeneratedCodeInfo_Annotation : Protobuf.Decode.Decoder GeneratedCodeInfo_Annotation
decodeGeneratedCodeInfo_Annotation =
    Protobuf.Decode.message
        defaultGeneratedCodeInfo_Annotation
        [ Protobuf.Decode.repeated 1 Protobuf.Decode.int32 .path (\a r -> { r | path = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | sourceFile = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.int32 (\a r -> { r | begin = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.int32 (\a r -> { r | end = a })
        ]


{-| Encode a `GeneratedCodeInfo_Annotation` to Bytes


-}
encodeGeneratedCodeInfo_Annotation : GeneratedCodeInfo_Annotation -> Protobuf.Encode.Encoder
encodeGeneratedCodeInfo_Annotation value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.list Protobuf.Encode.int32 value.path )
        , ( 2, Protobuf.Encode.string value.sourceFile )
        , ( 3, Protobuf.Encode.int32 value.begin )
        , ( 4, Protobuf.Encode.int32 value.end )
        ]


{-| `GeneratedCodeInfo_Annotation` message


-}
type alias GeneratedCodeInfo_Annotation =
    { path : List Int, sourceFile : String, begin : Int, end : Int }


{-| Decode a `SourceCodeInfo` from Bytes


-}
defaultSourceCodeInfo : SourceCodeInfo
defaultSourceCodeInfo =
    { location = [] }


{-| Decode a `SourceCodeInfo` from Bytes


-}
decodeSourceCodeInfo : Protobuf.Decode.Decoder SourceCodeInfo
decodeSourceCodeInfo =
    Protobuf.Decode.message
        defaultSourceCodeInfo
        [ Protobuf.Decode.repeated 1 decodeSourceCodeInfo_Location .location (\a r -> { r | location = a }) ]


{-| Encode a `SourceCodeInfo` to Bytes


-}
encodeSourceCodeInfo : SourceCodeInfo -> Protobuf.Encode.Encoder
encodeSourceCodeInfo value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.list encodeSourceCodeInfo_Location value.location ) ]


{-| `SourceCodeInfo` message


-}
type alias SourceCodeInfo =
    { location : List SourceCodeInfo_Location }


{-| Decode a `SourceCodeInfo_Location` from Bytes


-}
defaultSourceCodeInfo_Location : SourceCodeInfo_Location
defaultSourceCodeInfo_Location =
    { path = [], span = [], leadingComments = "", trailingComments = "", leadingDetachedComments = [] }


{-| Decode a `SourceCodeInfo_Location` from Bytes


-}
decodeSourceCodeInfo_Location : Protobuf.Decode.Decoder SourceCodeInfo_Location
decodeSourceCodeInfo_Location =
    Protobuf.Decode.message
        defaultSourceCodeInfo_Location
        [ Protobuf.Decode.repeated 1 Protobuf.Decode.int32 .path (\a r -> { r | path = a })
        , Protobuf.Decode.repeated 2 Protobuf.Decode.int32 .span (\a r -> { r | span = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | leadingComments = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.string (\a r -> { r | trailingComments = a })
        , Protobuf.Decode.repeated
            6
            Protobuf.Decode.string
            .leadingDetachedComments
            (\a r -> { r | leadingDetachedComments = a })
        ]


{-| Encode a `SourceCodeInfo_Location` to Bytes


-}
encodeSourceCodeInfo_Location : SourceCodeInfo_Location -> Protobuf.Encode.Encoder
encodeSourceCodeInfo_Location value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.list Protobuf.Encode.int32 value.path )
        , ( 2, Protobuf.Encode.list Protobuf.Encode.int32 value.span )
        , ( 3, Protobuf.Encode.string value.leadingComments )
        , ( 4, Protobuf.Encode.string value.trailingComments )
        , ( 6, Protobuf.Encode.list Protobuf.Encode.string value.leadingDetachedComments )
        ]


{-| `SourceCodeInfo_Location` message


-}
type alias SourceCodeInfo_Location =
    { path : List Int
    , span : List Int
    , leadingComments : String
    , trailingComments : String
    , leadingDetachedComments : List String
    }


{-| Decode a `UninterpretedOption` from Bytes


-}
defaultUninterpretedOption : UninterpretedOption
defaultUninterpretedOption =
    { name = []
    , identifierValue = ""
    , positiveIntValue = 0
    , negativeIntValue = 0
    , doubleValue = 0
    , stringValue = (Protobuf.Encode.encode <| Protobuf.Encode.string "")
    , aggregateValue = ""
    }


{-| Decode a `UninterpretedOption` from Bytes


-}
decodeUninterpretedOption : Protobuf.Decode.Decoder UninterpretedOption
decodeUninterpretedOption =
    Protobuf.Decode.message
        defaultUninterpretedOption
        [ Protobuf.Decode.repeated 2 decodeUninterpretedOption_NamePart .name (\a r -> { r | name = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | identifierValue = a })
        , Protobuf.Decode.optional 4 Protobuf.Decode.int32 (\a r -> { r | positiveIntValue = a })
        , Protobuf.Decode.optional 5 Protobuf.Decode.int32 (\a r -> { r | negativeIntValue = a })
        , Protobuf.Decode.optional 6 Protobuf.Decode.float (\a r -> { r | doubleValue = a })
        , Protobuf.Decode.optional 7 Protobuf.Decode.bytes (\a r -> { r | stringValue = a })
        , Protobuf.Decode.optional 8 Protobuf.Decode.string (\a r -> { r | aggregateValue = a })
        ]


{-| Encode a `UninterpretedOption` to Bytes


-}
encodeUninterpretedOption : UninterpretedOption -> Protobuf.Encode.Encoder
encodeUninterpretedOption value =
    Protobuf.Encode.message
        [ ( 2, Protobuf.Encode.list encodeUninterpretedOption_NamePart value.name )
        , ( 3, Protobuf.Encode.string value.identifierValue )
        , ( 4, Protobuf.Encode.int32 value.positiveIntValue )
        , ( 5, Protobuf.Encode.int32 value.negativeIntValue )
        , ( 6, Protobuf.Encode.float value.doubleValue )
        , ( 7, Protobuf.Encode.bytes value.stringValue )
        , ( 8, Protobuf.Encode.string value.aggregateValue )
        ]


{-| `UninterpretedOption` message


-}
type alias UninterpretedOption =
    { name : List UninterpretedOption_NamePart
    , identifierValue : String
    , positiveIntValue : Int
    , negativeIntValue : Int
    , doubleValue : Float
    , stringValue : Bytes.Bytes
    , aggregateValue : String
    }


{-| Decode a `UninterpretedOption_NamePart` from Bytes


-}
defaultUninterpretedOption_NamePart : UninterpretedOption_NamePart
defaultUninterpretedOption_NamePart =
    { namePart = "", isExtension = False }


{-| Decode a `UninterpretedOption_NamePart` from Bytes


-}
decodeUninterpretedOption_NamePart : Protobuf.Decode.Decoder UninterpretedOption_NamePart
decodeUninterpretedOption_NamePart =
    Protobuf.Decode.message
        defaultUninterpretedOption_NamePart
        [ Protobuf.Decode.required 1 Protobuf.Decode.string (\a r -> { r | namePart = a })
        , Protobuf.Decode.required 2 Protobuf.Decode.bool (\a r -> { r | isExtension = a })
        ]


{-| Encode a `UninterpretedOption_NamePart` to Bytes


-}
encodeUninterpretedOption_NamePart : UninterpretedOption_NamePart -> Protobuf.Encode.Encoder
encodeUninterpretedOption_NamePart value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.namePart ), ( 2, Protobuf.Encode.bool value.isExtension ) ]


{-| `UninterpretedOption_NamePart` message


-}
type alias UninterpretedOption_NamePart =
    { namePart : String, isExtension : Bool }


{-| Decode a `MethodOptions` from Bytes


-}
defaultMethodOptions : MethodOptions
defaultMethodOptions =
    { deprecated = False
    , idempotencyLevel = MethodOptions_IdempotencyLevel_IDEMPOTENCYUNKNOWN
    , uninterpretedOption = []
    }


{-| Decode a `MethodOptions` from Bytes


-}
decodeMethodOptions : Protobuf.Decode.Decoder MethodOptions
decodeMethodOptions =
    Protobuf.Decode.message
        defaultMethodOptions
        [ Protobuf.Decode.optional 33 Protobuf.Decode.bool (\a r -> { r | deprecated = a })
        , Protobuf.Decode.optional 34 decodeMethodOptions_IdempotencyLevel (\a r -> { r | idempotencyLevel = a })
        , Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `MethodOptions` to Bytes


-}
encodeMethodOptions : MethodOptions -> Protobuf.Encode.Encoder
encodeMethodOptions value =
    Protobuf.Encode.message
        [ ( 33, Protobuf.Encode.bool value.deprecated )
        , ( 34, encodeMethodOptions_IdempotencyLevel value.idempotencyLevel )
        , ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption )
        ]


{-| `MethodOptions` message


-}
type alias MethodOptions =
    { deprecated : Bool
    , idempotencyLevel : MethodOptions_IdempotencyLevel
    , uninterpretedOption : List UninterpretedOption
    }


{-| Decode a `ServiceOptions` from Bytes


-}
defaultServiceOptions : ServiceOptions
defaultServiceOptions =
    { deprecated = False, uninterpretedOption = [] }


{-| Decode a `ServiceOptions` from Bytes


-}
decodeServiceOptions : Protobuf.Decode.Decoder ServiceOptions
decodeServiceOptions =
    Protobuf.Decode.message
        defaultServiceOptions
        [ Protobuf.Decode.optional 33 Protobuf.Decode.bool (\a r -> { r | deprecated = a })
        , Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `ServiceOptions` to Bytes


-}
encodeServiceOptions : ServiceOptions -> Protobuf.Encode.Encoder
encodeServiceOptions value =
    Protobuf.Encode.message
        [ ( 33, Protobuf.Encode.bool value.deprecated )
        , ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption )
        ]


{-| `ServiceOptions` message


-}
type alias ServiceOptions =
    { deprecated : Bool, uninterpretedOption : List UninterpretedOption }


{-| Decode a `EnumValueOptions` from Bytes


-}
defaultEnumValueOptions : EnumValueOptions
defaultEnumValueOptions =
    { deprecated = False, uninterpretedOption = [] }


{-| Decode a `EnumValueOptions` from Bytes


-}
decodeEnumValueOptions : Protobuf.Decode.Decoder EnumValueOptions
decodeEnumValueOptions =
    Protobuf.Decode.message
        defaultEnumValueOptions
        [ Protobuf.Decode.optional 1 Protobuf.Decode.bool (\a r -> { r | deprecated = a })
        , Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `EnumValueOptions` to Bytes


-}
encodeEnumValueOptions : EnumValueOptions -> Protobuf.Encode.Encoder
encodeEnumValueOptions value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.bool value.deprecated )
        , ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption )
        ]


{-| `EnumValueOptions` message


-}
type alias EnumValueOptions =
    { deprecated : Bool, uninterpretedOption : List UninterpretedOption }


{-| Decode a `EnumOptions` from Bytes


-}
defaultEnumOptions : EnumOptions
defaultEnumOptions =
    { allowAlias = False, deprecated = False, uninterpretedOption = [] }


{-| Decode a `EnumOptions` from Bytes


-}
decodeEnumOptions : Protobuf.Decode.Decoder EnumOptions
decodeEnumOptions =
    Protobuf.Decode.message
        defaultEnumOptions
        [ Protobuf.Decode.optional 2 Protobuf.Decode.bool (\a r -> { r | allowAlias = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.bool (\a r -> { r | deprecated = a })
        , Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `EnumOptions` to Bytes


-}
encodeEnumOptions : EnumOptions -> Protobuf.Encode.Encoder
encodeEnumOptions value =
    Protobuf.Encode.message
        [ ( 2, Protobuf.Encode.bool value.allowAlias )
        , ( 3, Protobuf.Encode.bool value.deprecated )
        , ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption )
        ]


{-| `EnumOptions` message


-}
type alias EnumOptions =
    { allowAlias : Bool, deprecated : Bool, uninterpretedOption : List UninterpretedOption }


{-| Decode a `OneofOptions` from Bytes


-}
defaultOneofOptions : OneofOptions
defaultOneofOptions =
    { uninterpretedOption = [] }


{-| Decode a `OneofOptions` from Bytes


-}
decodeOneofOptions : Protobuf.Decode.Decoder OneofOptions
decodeOneofOptions =
    Protobuf.Decode.message
        defaultOneofOptions
        [ Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `OneofOptions` to Bytes


-}
encodeOneofOptions : OneofOptions -> Protobuf.Encode.Encoder
encodeOneofOptions value =
    Protobuf.Encode.message [ ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption ) ]


{-| `OneofOptions` message


-}
type alias OneofOptions =
    { uninterpretedOption : List UninterpretedOption }


{-| Decode a `FieldOptions` from Bytes


-}
defaultFieldOptions : FieldOptions
defaultFieldOptions =
    { ctype = FieldOptions_CType_STRING
    , packed = False
    , jstype = FieldOptions_JSType_JSNORMAL
    , lazy = False
    , deprecated = False
    , weak = False
    , uninterpretedOption = []
    }


{-| Decode a `FieldOptions` from Bytes


-}
decodeFieldOptions : Protobuf.Decode.Decoder FieldOptions
decodeFieldOptions =
    Protobuf.Decode.message
        defaultFieldOptions
        [ Protobuf.Decode.optional 1 decodeFieldOptions_CType (\a r -> { r | ctype = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.bool (\a r -> { r | packed = a })
        , Protobuf.Decode.optional 6 decodeFieldOptions_JSType (\a r -> { r | jstype = a })
        , Protobuf.Decode.optional 5 Protobuf.Decode.bool (\a r -> { r | lazy = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.bool (\a r -> { r | deprecated = a })
        , Protobuf.Decode.optional 10 Protobuf.Decode.bool (\a r -> { r | weak = a })
        , Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `FieldOptions` to Bytes


-}
encodeFieldOptions : FieldOptions -> Protobuf.Encode.Encoder
encodeFieldOptions value =
    Protobuf.Encode.message
        [ ( 1, encodeFieldOptions_CType value.ctype )
        , ( 2, Protobuf.Encode.bool value.packed )
        , ( 6, encodeFieldOptions_JSType value.jstype )
        , ( 5, Protobuf.Encode.bool value.lazy )
        , ( 3, Protobuf.Encode.bool value.deprecated )
        , ( 10, Protobuf.Encode.bool value.weak )
        , ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption )
        ]


{-| `FieldOptions` message


-}
type alias FieldOptions =
    { ctype : FieldOptions_CType
    , packed : Bool
    , jstype : FieldOptions_JSType
    , lazy : Bool
    , deprecated : Bool
    , weak : Bool
    , uninterpretedOption : List UninterpretedOption
    }


{-| Decode a `MessageOptions` from Bytes


-}
defaultMessageOptions : MessageOptions
defaultMessageOptions =
    { messageSetWireFormat = False
    , noStandardDescriptorAccessor = False
    , deprecated = False
    , mapEntry = False
    , uninterpretedOption = []
    }


{-| Decode a `MessageOptions` from Bytes


-}
decodeMessageOptions : Protobuf.Decode.Decoder MessageOptions
decodeMessageOptions =
    Protobuf.Decode.message
        defaultMessageOptions
        [ Protobuf.Decode.optional 1 Protobuf.Decode.bool (\a r -> { r | messageSetWireFormat = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.bool (\a r -> { r | noStandardDescriptorAccessor = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.bool (\a r -> { r | deprecated = a })
        , Protobuf.Decode.optional 7 Protobuf.Decode.bool (\a r -> { r | mapEntry = a })
        , Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `MessageOptions` to Bytes


-}
encodeMessageOptions : MessageOptions -> Protobuf.Encode.Encoder
encodeMessageOptions value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.bool value.messageSetWireFormat )
        , ( 2, Protobuf.Encode.bool value.noStandardDescriptorAccessor )
        , ( 3, Protobuf.Encode.bool value.deprecated )
        , ( 7, Protobuf.Encode.bool value.mapEntry )
        , ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption )
        ]


{-| `MessageOptions` message


-}
type alias MessageOptions =
    { messageSetWireFormat : Bool
    , noStandardDescriptorAccessor : Bool
    , deprecated : Bool
    , mapEntry : Bool
    , uninterpretedOption : List UninterpretedOption
    }


{-| Decode a `FileOptions` from Bytes


-}
defaultFileOptions : FileOptions
defaultFileOptions =
    { javaPackage = ""
    , javaOuterClassname = ""
    , javaMultipleFiles = False
    , javaGenerateEqualsAndHash = False
    , javaStringCheckUtf8 = False
    , optimizeFor = FileOptions_OptimizeMode_SPEED
    , goPackage = ""
    , ccGenericServices = False
    , javaGenericServices = False
    , pyGenericServices = False
    , phpGenericServices = False
    , deprecated = False
    , ccEnableArenas = True
    , objcClassPrefix = ""
    , csharpNamespace = ""
    , swiftPrefix = ""
    , phpClassPrefix = ""
    , phpNamespace = ""
    , phpMetadataNamespace = ""
    , rubyPackage = ""
    , uninterpretedOption = []
    }


{-| Decode a `FileOptions` from Bytes


-}
decodeFileOptions : Protobuf.Decode.Decoder FileOptions
decodeFileOptions =
    Protobuf.Decode.message
        defaultFileOptions
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | javaPackage = a })
        , Protobuf.Decode.optional 8 Protobuf.Decode.string (\a r -> { r | javaOuterClassname = a })
        , Protobuf.Decode.optional 10 Protobuf.Decode.bool (\a r -> { r | javaMultipleFiles = a })
        , Protobuf.Decode.optional 20 Protobuf.Decode.bool (\a r -> { r | javaGenerateEqualsAndHash = a })
        , Protobuf.Decode.optional 27 Protobuf.Decode.bool (\a r -> { r | javaStringCheckUtf8 = a })
        , Protobuf.Decode.optional 9 decodeFileOptions_OptimizeMode (\a r -> { r | optimizeFor = a })
        , Protobuf.Decode.optional 11 Protobuf.Decode.string (\a r -> { r | goPackage = a })
        , Protobuf.Decode.optional 16 Protobuf.Decode.bool (\a r -> { r | ccGenericServices = a })
        , Protobuf.Decode.optional 17 Protobuf.Decode.bool (\a r -> { r | javaGenericServices = a })
        , Protobuf.Decode.optional 18 Protobuf.Decode.bool (\a r -> { r | pyGenericServices = a })
        , Protobuf.Decode.optional 42 Protobuf.Decode.bool (\a r -> { r | phpGenericServices = a })
        , Protobuf.Decode.optional 23 Protobuf.Decode.bool (\a r -> { r | deprecated = a })
        , Protobuf.Decode.optional 31 Protobuf.Decode.bool (\a r -> { r | ccEnableArenas = a })
        , Protobuf.Decode.optional 36 Protobuf.Decode.string (\a r -> { r | objcClassPrefix = a })
        , Protobuf.Decode.optional 37 Protobuf.Decode.string (\a r -> { r | csharpNamespace = a })
        , Protobuf.Decode.optional 39 Protobuf.Decode.string (\a r -> { r | swiftPrefix = a })
        , Protobuf.Decode.optional 40 Protobuf.Decode.string (\a r -> { r | phpClassPrefix = a })
        , Protobuf.Decode.optional 41 Protobuf.Decode.string (\a r -> { r | phpNamespace = a })
        , Protobuf.Decode.optional 44 Protobuf.Decode.string (\a r -> { r | phpMetadataNamespace = a })
        , Protobuf.Decode.optional 45 Protobuf.Decode.string (\a r -> { r | rubyPackage = a })
        , Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `FileOptions` to Bytes


-}
encodeFileOptions : FileOptions -> Protobuf.Encode.Encoder
encodeFileOptions value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.javaPackage )
        , ( 8, Protobuf.Encode.string value.javaOuterClassname )
        , ( 10, Protobuf.Encode.bool value.javaMultipleFiles )
        , ( 20, Protobuf.Encode.bool value.javaGenerateEqualsAndHash )
        , ( 27, Protobuf.Encode.bool value.javaStringCheckUtf8 )
        , ( 9, encodeFileOptions_OptimizeMode value.optimizeFor )
        , ( 11, Protobuf.Encode.string value.goPackage )
        , ( 16, Protobuf.Encode.bool value.ccGenericServices )
        , ( 17, Protobuf.Encode.bool value.javaGenericServices )
        , ( 18, Protobuf.Encode.bool value.pyGenericServices )
        , ( 42, Protobuf.Encode.bool value.phpGenericServices )
        , ( 23, Protobuf.Encode.bool value.deprecated )
        , ( 31, Protobuf.Encode.bool value.ccEnableArenas )
        , ( 36, Protobuf.Encode.string value.objcClassPrefix )
        , ( 37, Protobuf.Encode.string value.csharpNamespace )
        , ( 39, Protobuf.Encode.string value.swiftPrefix )
        , ( 40, Protobuf.Encode.string value.phpClassPrefix )
        , ( 41, Protobuf.Encode.string value.phpNamespace )
        , ( 44, Protobuf.Encode.string value.phpMetadataNamespace )
        , ( 45, Protobuf.Encode.string value.rubyPackage )
        , ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption )
        ]


{-| `FileOptions` message


-}
type alias FileOptions =
    { javaPackage : String
    , javaOuterClassname : String
    , javaMultipleFiles : Bool
    , javaGenerateEqualsAndHash : Bool
    , javaStringCheckUtf8 : Bool
    , optimizeFor : FileOptions_OptimizeMode
    , goPackage : String
    , ccGenericServices : Bool
    , javaGenericServices : Bool
    , pyGenericServices : Bool
    , phpGenericServices : Bool
    , deprecated : Bool
    , ccEnableArenas : Bool
    , objcClassPrefix : String
    , csharpNamespace : String
    , swiftPrefix : String
    , phpClassPrefix : String
    , phpNamespace : String
    , phpMetadataNamespace : String
    , rubyPackage : String
    , uninterpretedOption : List UninterpretedOption
    }


{-| Decode a `MethodDescriptorProto` from Bytes


-}
defaultMethodDescriptorProto : MethodDescriptorProto
defaultMethodDescriptorProto =
    { name = "", inputType = "", outputType = "", options = Nothing, clientStreaming = False, serverStreaming = False }


{-| Decode a `MethodDescriptorProto` from Bytes


-}
decodeMethodDescriptorProto : Protobuf.Decode.Decoder MethodDescriptorProto
decodeMethodDescriptorProto =
    Protobuf.Decode.message
        defaultMethodDescriptorProto
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | inputType = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.string (\a r -> { r | outputType = a })
        , Protobuf.Decode.optional 4 (Protobuf.Decode.map Just decodeMethodOptions) (\a r -> { r | options = a })
        , Protobuf.Decode.optional 5 Protobuf.Decode.bool (\a r -> { r | clientStreaming = a })
        , Protobuf.Decode.optional 6 Protobuf.Decode.bool (\a r -> { r | serverStreaming = a })
        ]


{-| Encode a `MethodDescriptorProto` to Bytes


-}
encodeMethodDescriptorProto : MethodDescriptorProto -> Protobuf.Encode.Encoder
encodeMethodDescriptorProto value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.name )
        , ( 2, Protobuf.Encode.string value.inputType )
        , ( 3, Protobuf.Encode.string value.outputType )
        , ( 4, (Maybe.map encodeMethodOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        , ( 5, Protobuf.Encode.bool value.clientStreaming )
        , ( 6, Protobuf.Encode.bool value.serverStreaming )
        ]


{-| `MethodDescriptorProto` message


-}
type alias MethodDescriptorProto =
    { name : String
    , inputType : String
    , outputType : String
    , options : Maybe MethodOptions
    , clientStreaming : Bool
    , serverStreaming : Bool
    }


{-| Decode a `ServiceDescriptorProto` from Bytes


-}
defaultServiceDescriptorProto : ServiceDescriptorProto
defaultServiceDescriptorProto =
    { name = "", method = [], options = Nothing }


{-| Decode a `ServiceDescriptorProto` from Bytes


-}
decodeServiceDescriptorProto : Protobuf.Decode.Decoder ServiceDescriptorProto
decodeServiceDescriptorProto =
    Protobuf.Decode.message
        defaultServiceDescriptorProto
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.repeated 2 decodeMethodDescriptorProto .method (\a r -> { r | method = a })
        , Protobuf.Decode.optional 3 (Protobuf.Decode.map Just decodeServiceOptions) (\a r -> { r | options = a })
        ]


{-| Encode a `ServiceDescriptorProto` to Bytes


-}
encodeServiceDescriptorProto : ServiceDescriptorProto -> Protobuf.Encode.Encoder
encodeServiceDescriptorProto value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.name )
        , ( 2, Protobuf.Encode.list encodeMethodDescriptorProto value.method )
        , ( 3, (Maybe.map encodeServiceOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        ]


{-| `ServiceDescriptorProto` message


-}
type alias ServiceDescriptorProto =
    { name : String, method : List MethodDescriptorProto, options : Maybe ServiceOptions }


{-| Decode a `EnumValueDescriptorProto` from Bytes


-}
defaultEnumValueDescriptorProto : EnumValueDescriptorProto
defaultEnumValueDescriptorProto =
    { name = "", number = 0, options = Nothing }


{-| Decode a `EnumValueDescriptorProto` from Bytes


-}
decodeEnumValueDescriptorProto : Protobuf.Decode.Decoder EnumValueDescriptorProto
decodeEnumValueDescriptorProto =
    Protobuf.Decode.message
        defaultEnumValueDescriptorProto
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.int32 (\a r -> { r | number = a })
        , Protobuf.Decode.optional 3 (Protobuf.Decode.map Just decodeEnumValueOptions) (\a r -> { r | options = a })
        ]


{-| Encode a `EnumValueDescriptorProto` to Bytes


-}
encodeEnumValueDescriptorProto : EnumValueDescriptorProto -> Protobuf.Encode.Encoder
encodeEnumValueDescriptorProto value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.name )
        , ( 2, Protobuf.Encode.int32 value.number )
        , ( 3, (Maybe.map encodeEnumValueOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        ]


{-| `EnumValueDescriptorProto` message


-}
type alias EnumValueDescriptorProto =
    { name : String, number : Int, options : Maybe EnumValueOptions }


{-| Decode a `EnumDescriptorProto` from Bytes


-}
defaultEnumDescriptorProto : EnumDescriptorProto
defaultEnumDescriptorProto =
    { name = "", value = [], options = Nothing, reservedRange = [], reservedName = [] }


{-| Decode a `EnumDescriptorProto` from Bytes


-}
decodeEnumDescriptorProto : Protobuf.Decode.Decoder EnumDescriptorProto
decodeEnumDescriptorProto =
    Protobuf.Decode.message
        defaultEnumDescriptorProto
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.repeated 2 decodeEnumValueDescriptorProto .value (\a r -> { r | value = a })
        , Protobuf.Decode.optional 3 (Protobuf.Decode.map Just decodeEnumOptions) (\a r -> { r | options = a })
        , Protobuf.Decode.repeated
            4
            decodeEnumDescriptorProto_EnumReservedRange
            .reservedRange
            (\a r -> { r | reservedRange = a })
        , Protobuf.Decode.repeated 5 Protobuf.Decode.string .reservedName (\a r -> { r | reservedName = a })
        ]


{-| Encode a `EnumDescriptorProto` to Bytes


-}
encodeEnumDescriptorProto : EnumDescriptorProto -> Protobuf.Encode.Encoder
encodeEnumDescriptorProto value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.name )
        , ( 2, Protobuf.Encode.list encodeEnumValueDescriptorProto value.value )
        , ( 3, (Maybe.map encodeEnumOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        , ( 4, Protobuf.Encode.list encodeEnumDescriptorProto_EnumReservedRange value.reservedRange )
        , ( 5, Protobuf.Encode.list Protobuf.Encode.string value.reservedName )
        ]


{-| `EnumDescriptorProto` message


-}
type alias EnumDescriptorProto =
    { name : String
    , value : List EnumValueDescriptorProto
    , options : Maybe EnumOptions
    , reservedRange : List EnumDescriptorProto_EnumReservedRange
    , reservedName : List String
    }


{-| Decode a `EnumDescriptorProto_EnumReservedRange` from Bytes


-}
defaultEnumDescriptorProto_EnumReservedRange : EnumDescriptorProto_EnumReservedRange
defaultEnumDescriptorProto_EnumReservedRange =
    { start = 0, end = 0 }


{-| Decode a `EnumDescriptorProto_EnumReservedRange` from Bytes


-}
decodeEnumDescriptorProto_EnumReservedRange : Protobuf.Decode.Decoder EnumDescriptorProto_EnumReservedRange
decodeEnumDescriptorProto_EnumReservedRange =
    Protobuf.Decode.message
        defaultEnumDescriptorProto_EnumReservedRange
        [ Protobuf.Decode.optional 1 Protobuf.Decode.int32 (\a r -> { r | start = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.int32 (\a r -> { r | end = a })
        ]


{-| Encode a `EnumDescriptorProto_EnumReservedRange` to Bytes


-}
encodeEnumDescriptorProto_EnumReservedRange : EnumDescriptorProto_EnumReservedRange -> Protobuf.Encode.Encoder
encodeEnumDescriptorProto_EnumReservedRange value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.int32 value.start ), ( 2, Protobuf.Encode.int32 value.end ) ]


{-| `EnumDescriptorProto_EnumReservedRange` message


-}
type alias EnumDescriptorProto_EnumReservedRange =
    { start : Int, end : Int }


{-| Decode a `OneofDescriptorProto` from Bytes


-}
defaultOneofDescriptorProto : OneofDescriptorProto
defaultOneofDescriptorProto =
    { name = "", options = Nothing }


{-| Decode a `OneofDescriptorProto` from Bytes


-}
decodeOneofDescriptorProto : Protobuf.Decode.Decoder OneofDescriptorProto
decodeOneofDescriptorProto =
    Protobuf.Decode.message
        defaultOneofDescriptorProto
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.optional 2 (Protobuf.Decode.map Just decodeOneofOptions) (\a r -> { r | options = a })
        ]


{-| Encode a `OneofDescriptorProto` to Bytes


-}
encodeOneofDescriptorProto : OneofDescriptorProto -> Protobuf.Encode.Encoder
encodeOneofDescriptorProto value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.name )
        , ( 2, (Maybe.map encodeOneofOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        ]


{-| `OneofDescriptorProto` message


-}
type alias OneofDescriptorProto =
    { name : String, options : Maybe OneofOptions }


{-| Decode a `FieldDescriptorProto` from Bytes


-}
defaultFieldDescriptorProto : FieldDescriptorProto
defaultFieldDescriptorProto =
    { name = ""
    , number = 0
    , label = FieldDescriptorProto_Label_LABELOPTIONAL
    , type_ = FieldDescriptorProto_Type_TYPEDOUBLE
    , typeName = ""
    , extendee = ""
    , defaultValue = ""
    , oneofIndex = -1
    , jsonName = ""
    , options = Nothing
    , proto3Optional = False
    }


{-| Decode a `FieldDescriptorProto` from Bytes


-}
decodeFieldDescriptorProto : Protobuf.Decode.Decoder FieldDescriptorProto
decodeFieldDescriptorProto =
    Protobuf.Decode.message
        defaultFieldDescriptorProto
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.optional 3 Protobuf.Decode.int32 (\a r -> { r | number = a })
        , Protobuf.Decode.optional 4 decodeFieldDescriptorProto_Label (\a r -> { r | label = a })
        , Protobuf.Decode.optional 5 decodeFieldDescriptorProto_Type (\a r -> { r | type_ = a })
        , Protobuf.Decode.optional 6 Protobuf.Decode.string (\a r -> { r | typeName = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | extendee = a })
        , Protobuf.Decode.optional 7 Protobuf.Decode.string (\a r -> { r | defaultValue = a })
        , Protobuf.Decode.optional 9 Protobuf.Decode.int32 (\a r -> { r | oneofIndex = a })
        , Protobuf.Decode.optional 10 Protobuf.Decode.string (\a r -> { r | jsonName = a })
        , Protobuf.Decode.optional 8 (Protobuf.Decode.map Just decodeFieldOptions) (\a r -> { r | options = a })
        , Protobuf.Decode.optional 17 Protobuf.Decode.bool (\a r -> { r | proto3Optional = a })
        ]


{-| Encode a `FieldDescriptorProto` to Bytes


-}
encodeFieldDescriptorProto : FieldDescriptorProto -> Protobuf.Encode.Encoder
encodeFieldDescriptorProto value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.name )
        , ( 3, Protobuf.Encode.int32 value.number )
        , ( 4, encodeFieldDescriptorProto_Label value.label )
        , ( 5, encodeFieldDescriptorProto_Type value.type_ )
        , ( 6, Protobuf.Encode.string value.typeName )
        , ( 2, Protobuf.Encode.string value.extendee )
        , ( 7, Protobuf.Encode.string value.defaultValue )
        , ( 9, Protobuf.Encode.int32 value.oneofIndex )
        , ( 10, Protobuf.Encode.string value.jsonName )
        , ( 8, (Maybe.map encodeFieldOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        , ( 17, Protobuf.Encode.bool value.proto3Optional )
        ]


{-| `FieldDescriptorProto` message


-}
type alias FieldDescriptorProto =
    { name : String
    , number : Int
    , label : FieldDescriptorProto_Label
    , type_ : FieldDescriptorProto_Type
    , typeName : String
    , extendee : String
    , defaultValue : String
    , oneofIndex : Int
    , jsonName : String
    , options : Maybe FieldOptions
    , proto3Optional : Bool
    }


{-| Decode a `ExtensionRangeOptions` from Bytes


-}
defaultExtensionRangeOptions : ExtensionRangeOptions
defaultExtensionRangeOptions =
    { uninterpretedOption = [] }


{-| Decode a `ExtensionRangeOptions` from Bytes


-}
decodeExtensionRangeOptions : Protobuf.Decode.Decoder ExtensionRangeOptions
decodeExtensionRangeOptions =
    Protobuf.Decode.message
        defaultExtensionRangeOptions
        [ Protobuf.Decode.repeated
            999
            decodeUninterpretedOption
            .uninterpretedOption
            (\a r -> { r | uninterpretedOption = a })
        ]


{-| Encode a `ExtensionRangeOptions` to Bytes


-}
encodeExtensionRangeOptions : ExtensionRangeOptions -> Protobuf.Encode.Encoder
encodeExtensionRangeOptions value =
    Protobuf.Encode.message [ ( 999, Protobuf.Encode.list encodeUninterpretedOption value.uninterpretedOption ) ]


{-| `ExtensionRangeOptions` message


-}
type alias ExtensionRangeOptions =
    { uninterpretedOption : List UninterpretedOption }


{-| 
-}
unwrapDescriptorProto_ : DescriptorProto_ -> DescriptorProto
unwrapDescriptorProto_ (DescriptorProto_ wrapped) =
    wrapped


{-| 
-}
type DescriptorProto_
    = DescriptorProto_ DescriptorProto


{-| Decode a `DescriptorProto` from Bytes


-}
defaultDescriptorProto : DescriptorProto
defaultDescriptorProto =
    { name = ""
    , field = []
    , extension = []
    , nestedType = []
    , enumType = []
    , extensionRange = []
    , oneofDecl = []
    , options = Nothing
    , reservedRange = []
    , reservedName = []
    }


{-| Decode a `DescriptorProto` from Bytes


-}
decodeDescriptorProto : Protobuf.Decode.Decoder DescriptorProto
decodeDescriptorProto =
    Protobuf.Decode.message
        defaultDescriptorProto
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.repeated 2 decodeFieldDescriptorProto .field (\a r -> { r | field = a })
        , Protobuf.Decode.repeated 6 decodeFieldDescriptorProto .extension (\a r -> { r | extension = a })
        , Protobuf.Decode.repeated
            3
            (Protobuf.Decode.map DescriptorProto_ <| Protobuf.Decode.lazy <| \_ -> decodeDescriptorProto)
            .nestedType
            (\a r -> { r | nestedType = a })
        , Protobuf.Decode.repeated 4 decodeEnumDescriptorProto .enumType (\a r -> { r | enumType = a })
        , Protobuf.Decode.repeated
            5
            decodeDescriptorProto_ExtensionRange
            .extensionRange
            (\a r -> { r | extensionRange = a })
        , Protobuf.Decode.repeated 8 decodeOneofDescriptorProto .oneofDecl (\a r -> { r | oneofDecl = a })
        , Protobuf.Decode.optional 7 (Protobuf.Decode.map Just decodeMessageOptions) (\a r -> { r | options = a })
        , Protobuf.Decode.repeated
            9
            decodeDescriptorProto_ReservedRange
            .reservedRange
            (\a r -> { r | reservedRange = a })
        , Protobuf.Decode.repeated 10 Protobuf.Decode.string .reservedName (\a r -> { r | reservedName = a })
        ]


{-| Encode a `DescriptorProto` to Bytes


-}
encodeDescriptorProto : DescriptorProto -> Protobuf.Encode.Encoder
encodeDescriptorProto value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.name )
        , ( 2, Protobuf.Encode.list encodeFieldDescriptorProto value.field )
        , ( 6, Protobuf.Encode.list encodeFieldDescriptorProto value.extension )
        , ( 3, Protobuf.Encode.list (unwrapDescriptorProto_ >> encodeDescriptorProto) value.nestedType )
        , ( 4, Protobuf.Encode.list encodeEnumDescriptorProto value.enumType )
        , ( 5, Protobuf.Encode.list encodeDescriptorProto_ExtensionRange value.extensionRange )
        , ( 8, Protobuf.Encode.list encodeOneofDescriptorProto value.oneofDecl )
        , ( 7, (Maybe.map encodeMessageOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        , ( 9, Protobuf.Encode.list encodeDescriptorProto_ReservedRange value.reservedRange )
        , ( 10, Protobuf.Encode.list Protobuf.Encode.string value.reservedName )
        ]


{-| `DescriptorProto` message


-}
type alias DescriptorProto =
    { name : String
    , field : List FieldDescriptorProto
    , extension : List FieldDescriptorProto
    , nestedType : List DescriptorProto_
    , enumType : List EnumDescriptorProto
    , extensionRange : List DescriptorProto_ExtensionRange
    , oneofDecl : List OneofDescriptorProto
    , options : Maybe MessageOptions
    , reservedRange : List DescriptorProto_ReservedRange
    , reservedName : List String
    }


{-| Decode a `DescriptorProto_ReservedRange` from Bytes


-}
defaultDescriptorProto_ReservedRange : DescriptorProto_ReservedRange
defaultDescriptorProto_ReservedRange =
    { start = 0, end = 0 }


{-| Decode a `DescriptorProto_ReservedRange` from Bytes


-}
decodeDescriptorProto_ReservedRange : Protobuf.Decode.Decoder DescriptorProto_ReservedRange
decodeDescriptorProto_ReservedRange =
    Protobuf.Decode.message
        defaultDescriptorProto_ReservedRange
        [ Protobuf.Decode.optional 1 Protobuf.Decode.int32 (\a r -> { r | start = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.int32 (\a r -> { r | end = a })
        ]


{-| Encode a `DescriptorProto_ReservedRange` to Bytes


-}
encodeDescriptorProto_ReservedRange : DescriptorProto_ReservedRange -> Protobuf.Encode.Encoder
encodeDescriptorProto_ReservedRange value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.int32 value.start ), ( 2, Protobuf.Encode.int32 value.end ) ]


{-| `DescriptorProto_ReservedRange` message


-}
type alias DescriptorProto_ReservedRange =
    { start : Int, end : Int }


{-| Decode a `DescriptorProto_ExtensionRange` from Bytes


-}
defaultDescriptorProto_ExtensionRange : DescriptorProto_ExtensionRange
defaultDescriptorProto_ExtensionRange =
    { start = 0, end = 0, options = Nothing }


{-| Decode a `DescriptorProto_ExtensionRange` from Bytes


-}
decodeDescriptorProto_ExtensionRange : Protobuf.Decode.Decoder DescriptorProto_ExtensionRange
decodeDescriptorProto_ExtensionRange =
    Protobuf.Decode.message
        defaultDescriptorProto_ExtensionRange
        [ Protobuf.Decode.optional 1 Protobuf.Decode.int32 (\a r -> { r | start = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.int32 (\a r -> { r | end = a })
        , Protobuf.Decode.optional
            3
            (Protobuf.Decode.map Just decodeExtensionRangeOptions)
            (\a r -> { r | options = a })
        ]


{-| Encode a `DescriptorProto_ExtensionRange` to Bytes


-}
encodeDescriptorProto_ExtensionRange : DescriptorProto_ExtensionRange -> Protobuf.Encode.Encoder
encodeDescriptorProto_ExtensionRange value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.int32 value.start )
        , ( 2, Protobuf.Encode.int32 value.end )
        , ( 3, (Maybe.map encodeExtensionRangeOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        ]


{-| `DescriptorProto_ExtensionRange` message


-}
type alias DescriptorProto_ExtensionRange =
    { start : Int, end : Int, options : Maybe ExtensionRangeOptions }


{-| Decode a `FileDescriptorProto` from Bytes


-}
defaultFileDescriptorProto : FileDescriptorProto
defaultFileDescriptorProto =
    { name = ""
    , package = ""
    , dependency = []
    , publicDependency = []
    , weakDependency = []
    , messageType = []
    , enumType = []
    , service = []
    , extension = []
    , options = Nothing
    , sourceCodeInfo = Nothing
    , syntax = ""
    }


{-| Decode a `FileDescriptorProto` from Bytes


-}
decodeFileDescriptorProto : Protobuf.Decode.Decoder FileDescriptorProto
decodeFileDescriptorProto =
    Protobuf.Decode.message
        defaultFileDescriptorProto
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a })
        , Protobuf.Decode.optional 2 Protobuf.Decode.string (\a r -> { r | package = a })
        , Protobuf.Decode.repeated 3 Protobuf.Decode.string .dependency (\a r -> { r | dependency = a })
        , Protobuf.Decode.repeated 10 Protobuf.Decode.int32 .publicDependency (\a r -> { r | publicDependency = a })
        , Protobuf.Decode.repeated 11 Protobuf.Decode.int32 .weakDependency (\a r -> { r | weakDependency = a })
        , Protobuf.Decode.repeated 4 decodeDescriptorProto .messageType (\a r -> { r | messageType = a })
        , Protobuf.Decode.repeated 5 decodeEnumDescriptorProto .enumType (\a r -> { r | enumType = a })
        , Protobuf.Decode.repeated 6 decodeServiceDescriptorProto .service (\a r -> { r | service = a })
        , Protobuf.Decode.repeated 7 decodeFieldDescriptorProto .extension (\a r -> { r | extension = a })
        , Protobuf.Decode.optional 8 (Protobuf.Decode.map Just decodeFileOptions) (\a r -> { r | options = a })
        , Protobuf.Decode.optional
            9
            (Protobuf.Decode.map Just decodeSourceCodeInfo)
            (\a r -> { r | sourceCodeInfo = a })
        , Protobuf.Decode.optional 12 Protobuf.Decode.string (\a r -> { r | syntax = a })
        ]


{-| Encode a `FileDescriptorProto` to Bytes


-}
encodeFileDescriptorProto : FileDescriptorProto -> Protobuf.Encode.Encoder
encodeFileDescriptorProto value =
    Protobuf.Encode.message
        [ ( 1, Protobuf.Encode.string value.name )
        , ( 2, Protobuf.Encode.string value.package )
        , ( 3, Protobuf.Encode.list Protobuf.Encode.string value.dependency )
        , ( 10, Protobuf.Encode.list Protobuf.Encode.int32 value.publicDependency )
        , ( 11, Protobuf.Encode.list Protobuf.Encode.int32 value.weakDependency )
        , ( 4, Protobuf.Encode.list encodeDescriptorProto value.messageType )
        , ( 5, Protobuf.Encode.list encodeEnumDescriptorProto value.enumType )
        , ( 6, Protobuf.Encode.list encodeServiceDescriptorProto value.service )
        , ( 7, Protobuf.Encode.list encodeFieldDescriptorProto value.extension )
        , ( 8, (Maybe.map encodeFileOptions >> Maybe.withDefault Protobuf.Encode.none) value.options )
        , ( 9, (Maybe.map encodeSourceCodeInfo >> Maybe.withDefault Protobuf.Encode.none) value.sourceCodeInfo )
        , ( 12, Protobuf.Encode.string value.syntax )
        ]


{-| `FileDescriptorProto` message


-}
type alias FileDescriptorProto =
    { name : String
    , package : String
    , dependency : List String
    , publicDependency : List Int
    , weakDependency : List Int
    , messageType : List DescriptorProto
    , enumType : List EnumDescriptorProto
    , service : List ServiceDescriptorProto
    , extension : List FieldDescriptorProto
    , options : Maybe FileOptions
    , sourceCodeInfo : Maybe SourceCodeInfo
    , syntax : String
    }


{-| Decode a `FileDescriptorSet` from Bytes


-}
defaultFileDescriptorSet : FileDescriptorSet
defaultFileDescriptorSet =
    { file = [] }


{-| Decode a `FileDescriptorSet` from Bytes


-}
decodeFileDescriptorSet : Protobuf.Decode.Decoder FileDescriptorSet
decodeFileDescriptorSet =
    Protobuf.Decode.message
        defaultFileDescriptorSet
        [ Protobuf.Decode.repeated 1 decodeFileDescriptorProto .file (\a r -> { r | file = a }) ]


{-| Encode a `FileDescriptorSet` to Bytes


-}
encodeFileDescriptorSet : FileDescriptorSet -> Protobuf.Encode.Encoder
encodeFileDescriptorSet value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.list encodeFileDescriptorProto value.file ) ]


{-| `FileDescriptorSet` message


-}
type alias FileDescriptorSet =
    { file : List FileDescriptorProto }


{-| Encode a `MethodOptions_IdempotencyLevel` to Bytes


-}
encodeMethodOptions_IdempotencyLevel : MethodOptions_IdempotencyLevel -> Protobuf.Encode.Encoder
encodeMethodOptions_IdempotencyLevel value =
    Protobuf.Encode.int32 <|
        case value of
            MethodOptions_IdempotencyLevel_IDEMPOTENCYUNKNOWN ->
                0

            MethodOptions_IdempotencyLevel_NOSIDEEFFECTS ->
                1

            MethodOptions_IdempotencyLevel_IDEMPOTENT ->
                2


{-| Decode a `MethodOptions_IdempotencyLevel` from Bytes


-}
decodeMethodOptions_IdempotencyLevel : Protobuf.Decode.Decoder MethodOptions_IdempotencyLevel
decodeMethodOptions_IdempotencyLevel =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        MethodOptions_IdempotencyLevel_IDEMPOTENCYUNKNOWN

                    1 ->
                        MethodOptions_IdempotencyLevel_NOSIDEEFFECTS

                    2 ->
                        MethodOptions_IdempotencyLevel_IDEMPOTENT

                    _ ->
                        MethodOptions_IdempotencyLevel_IDEMPOTENCYUNKNOWN
            )


{-| `MethodOptions_IdempotencyLevel` enumeration


-}
type MethodOptions_IdempotencyLevel
    = MethodOptions_IdempotencyLevel_IDEMPOTENCYUNKNOWN
    | MethodOptions_IdempotencyLevel_NOSIDEEFFECTS
    | MethodOptions_IdempotencyLevel_IDEMPOTENT


{-| Encode a `FieldOptions_JSType` to Bytes


-}
encodeFieldOptions_JSType : FieldOptions_JSType -> Protobuf.Encode.Encoder
encodeFieldOptions_JSType value =
    Protobuf.Encode.int32 <|
        case value of
            FieldOptions_JSType_JSNORMAL ->
                0

            FieldOptions_JSType_JSSTRING ->
                1

            FieldOptions_JSType_JSNUMBER ->
                2


{-| Decode a `FieldOptions_JSType` from Bytes


-}
decodeFieldOptions_JSType : Protobuf.Decode.Decoder FieldOptions_JSType
decodeFieldOptions_JSType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        FieldOptions_JSType_JSNORMAL

                    1 ->
                        FieldOptions_JSType_JSSTRING

                    2 ->
                        FieldOptions_JSType_JSNUMBER

                    _ ->
                        FieldOptions_JSType_JSNORMAL
            )


{-| `FieldOptions_JSType` enumeration


-}
type FieldOptions_JSType
    = FieldOptions_JSType_JSNORMAL
    | FieldOptions_JSType_JSSTRING
    | FieldOptions_JSType_JSNUMBER


{-| Encode a `FieldOptions_CType` to Bytes


-}
encodeFieldOptions_CType : FieldOptions_CType -> Protobuf.Encode.Encoder
encodeFieldOptions_CType value =
    Protobuf.Encode.int32 <|
        case value of
            FieldOptions_CType_STRING ->
                0

            FieldOptions_CType_CORD ->
                1

            FieldOptions_CType_STRINGPIECE ->
                2


{-| Decode a `FieldOptions_CType` from Bytes


-}
decodeFieldOptions_CType : Protobuf.Decode.Decoder FieldOptions_CType
decodeFieldOptions_CType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        FieldOptions_CType_STRING

                    1 ->
                        FieldOptions_CType_CORD

                    2 ->
                        FieldOptions_CType_STRINGPIECE

                    _ ->
                        FieldOptions_CType_STRING
            )


{-| `FieldOptions_CType` enumeration


-}
type FieldOptions_CType
    = FieldOptions_CType_STRING
    | FieldOptions_CType_CORD
    | FieldOptions_CType_STRINGPIECE


{-| Encode a `FileOptions_OptimizeMode` to Bytes


-}
encodeFileOptions_OptimizeMode : FileOptions_OptimizeMode -> Protobuf.Encode.Encoder
encodeFileOptions_OptimizeMode value =
    Protobuf.Encode.int32 <|
        case value of
            FileOptions_OptimizeMode_SPEED ->
                1

            FileOptions_OptimizeMode_CODESIZE ->
                2

            FileOptions_OptimizeMode_LITERUNTIME ->
                3


{-| Decode a `FileOptions_OptimizeMode` from Bytes


-}
decodeFileOptions_OptimizeMode : Protobuf.Decode.Decoder FileOptions_OptimizeMode
decodeFileOptions_OptimizeMode =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    1 ->
                        FileOptions_OptimizeMode_SPEED

                    2 ->
                        FileOptions_OptimizeMode_CODESIZE

                    3 ->
                        FileOptions_OptimizeMode_LITERUNTIME

                    _ ->
                        FileOptions_OptimizeMode_SPEED
            )


{-| `FileOptions_OptimizeMode` enumeration


-}
type FileOptions_OptimizeMode
    = FileOptions_OptimizeMode_SPEED
    | FileOptions_OptimizeMode_CODESIZE
    | FileOptions_OptimizeMode_LITERUNTIME


{-| Encode a `FieldDescriptorProto_Label` to Bytes


-}
encodeFieldDescriptorProto_Label : FieldDescriptorProto_Label -> Protobuf.Encode.Encoder
encodeFieldDescriptorProto_Label value =
    Protobuf.Encode.int32 <|
        case value of
            FieldDescriptorProto_Label_LABELOPTIONAL ->
                1

            FieldDescriptorProto_Label_LABELREQUIRED ->
                2

            FieldDescriptorProto_Label_LABELREPEATED ->
                3


{-| Decode a `FieldDescriptorProto_Label` from Bytes


-}
decodeFieldDescriptorProto_Label : Protobuf.Decode.Decoder FieldDescriptorProto_Label
decodeFieldDescriptorProto_Label =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    1 ->
                        FieldDescriptorProto_Label_LABELOPTIONAL

                    2 ->
                        FieldDescriptorProto_Label_LABELREQUIRED

                    3 ->
                        FieldDescriptorProto_Label_LABELREPEATED

                    _ ->
                        FieldDescriptorProto_Label_LABELOPTIONAL
            )


{-| `FieldDescriptorProto_Label` enumeration


-}
type FieldDescriptorProto_Label
    = FieldDescriptorProto_Label_LABELOPTIONAL
    | FieldDescriptorProto_Label_LABELREQUIRED
    | FieldDescriptorProto_Label_LABELREPEATED


{-| Encode a `FieldDescriptorProto_Type` to Bytes


-}
encodeFieldDescriptorProto_Type : FieldDescriptorProto_Type -> Protobuf.Encode.Encoder
encodeFieldDescriptorProto_Type value =
    Protobuf.Encode.int32 <|
        case value of
            FieldDescriptorProto_Type_TYPEDOUBLE ->
                1

            FieldDescriptorProto_Type_TYPEFLOAT ->
                2

            FieldDescriptorProto_Type_TYPEINT64 ->
                3

            FieldDescriptorProto_Type_TYPEUINT64 ->
                4

            FieldDescriptorProto_Type_TYPEINT32 ->
                5

            FieldDescriptorProto_Type_TYPEFIXED64 ->
                6

            FieldDescriptorProto_Type_TYPEFIXED32 ->
                7

            FieldDescriptorProto_Type_TYPEBOOL ->
                8

            FieldDescriptorProto_Type_TYPESTRING ->
                9

            FieldDescriptorProto_Type_TYPEGROUP ->
                10

            FieldDescriptorProto_Type_TYPEMESSAGE ->
                11

            FieldDescriptorProto_Type_TYPEBYTES ->
                12

            FieldDescriptorProto_Type_TYPEUINT32 ->
                13

            FieldDescriptorProto_Type_TYPEENUM ->
                14

            FieldDescriptorProto_Type_TYPESFIXED32 ->
                15

            FieldDescriptorProto_Type_TYPESFIXED64 ->
                16

            FieldDescriptorProto_Type_TYPESINT32 ->
                17

            FieldDescriptorProto_Type_TYPESINT64 ->
                18


{-| Decode a `FieldDescriptorProto_Type` from Bytes


-}
decodeFieldDescriptorProto_Type : Protobuf.Decode.Decoder FieldDescriptorProto_Type
decodeFieldDescriptorProto_Type =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    1 ->
                        FieldDescriptorProto_Type_TYPEDOUBLE

                    2 ->
                        FieldDescriptorProto_Type_TYPEFLOAT

                    3 ->
                        FieldDescriptorProto_Type_TYPEINT64

                    4 ->
                        FieldDescriptorProto_Type_TYPEUINT64

                    5 ->
                        FieldDescriptorProto_Type_TYPEINT32

                    6 ->
                        FieldDescriptorProto_Type_TYPEFIXED64

                    7 ->
                        FieldDescriptorProto_Type_TYPEFIXED32

                    8 ->
                        FieldDescriptorProto_Type_TYPEBOOL

                    9 ->
                        FieldDescriptorProto_Type_TYPESTRING

                    10 ->
                        FieldDescriptorProto_Type_TYPEGROUP

                    11 ->
                        FieldDescriptorProto_Type_TYPEMESSAGE

                    12 ->
                        FieldDescriptorProto_Type_TYPEBYTES

                    13 ->
                        FieldDescriptorProto_Type_TYPEUINT32

                    14 ->
                        FieldDescriptorProto_Type_TYPEENUM

                    15 ->
                        FieldDescriptorProto_Type_TYPESFIXED32

                    16 ->
                        FieldDescriptorProto_Type_TYPESFIXED64

                    17 ->
                        FieldDescriptorProto_Type_TYPESINT32

                    18 ->
                        FieldDescriptorProto_Type_TYPESINT64

                    _ ->
                        FieldDescriptorProto_Type_TYPEDOUBLE
            )


{-| `FieldDescriptorProto_Type` enumeration


-}
type FieldDescriptorProto_Type
    = FieldDescriptorProto_Type_TYPEDOUBLE
    | FieldDescriptorProto_Type_TYPEFLOAT
    | FieldDescriptorProto_Type_TYPEINT64
    | FieldDescriptorProto_Type_TYPEUINT64
    | FieldDescriptorProto_Type_TYPEINT32
    | FieldDescriptorProto_Type_TYPEFIXED64
    | FieldDescriptorProto_Type_TYPEFIXED32
    | FieldDescriptorProto_Type_TYPEBOOL
    | FieldDescriptorProto_Type_TYPESTRING
    | FieldDescriptorProto_Type_TYPEGROUP
    | FieldDescriptorProto_Type_TYPEMESSAGE
    | FieldDescriptorProto_Type_TYPEBYTES
    | FieldDescriptorProto_Type_TYPEUINT32
    | FieldDescriptorProto_Type_TYPEENUM
    | FieldDescriptorProto_Type_TYPESFIXED32
    | FieldDescriptorProto_Type_TYPESFIXED64
    | FieldDescriptorProto_Type_TYPESINT32
    | FieldDescriptorProto_Type_TYPESINT64
