{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Hello exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.0.0-beta.1
- `protoc` 3.19.4
- the following specification files: `greeter.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version 1.2.0 or higher.


-}

import Proto.Hello.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| Default for HelloResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultHelloResponse : HelloResponse
defaultHelloResponse =
    Proto.Hello.Internals_.defaultProto__Hello__HelloResponse


{-| Declares how to decode a `HelloResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeHelloResponse : Protobuf.Decode.Decoder HelloResponse
decodeHelloResponse =
    Proto.Hello.Internals_.decodeProto__Hello__HelloResponse


{-| Declares how to encode a `HelloResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeHelloResponse : HelloResponse -> Protobuf.Encode.Encoder
encodeHelloResponse =
    Proto.Hello.Internals_.encodeProto__Hello__HelloResponse


{-| `HelloResponse` message


-}
type alias HelloResponse =
    Proto.Hello.Internals_.Proto__Hello__HelloResponse


{-| Default for HelloRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultHelloRequest : HelloRequest
defaultHelloRequest =
    Proto.Hello.Internals_.defaultProto__Hello__HelloRequest


{-| Declares how to decode a `HelloRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeHelloRequest : Protobuf.Decode.Decoder HelloRequest
decodeHelloRequest =
    Proto.Hello.Internals_.decodeProto__Hello__HelloRequest


{-| Declares how to encode a `HelloRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeHelloRequest : HelloRequest -> Protobuf.Encode.Encoder
encodeHelloRequest =
    Proto.Hello.Internals_.encodeProto__Hello__HelloRequest


{-| `HelloRequest` message


-}
type alias HelloRequest =
    Proto.Hello.Internals_.Proto__Hello__HelloRequest
