{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Hello.Internals_ exposing (Proto__Hello__HelloRequest, Proto__Hello__HelloResponse, decodeProto__Hello__HelloRequest, decodeProto__Hello__HelloResponse, defaultProto__Hello__HelloRequest, defaultProto__Hello__HelloResponse, encodeProto__Hello__HelloRequest, encodeProto__Hello__HelloResponse, fieldNumbersProto__Hello__HelloRequest, fieldNumbersProto__Hello__HelloResponse)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.0
- `protoc` 3.19.4
- the following specification files: `greeter.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version 1.2.0 or higher.

@docs Proto__Hello__HelloRequest, Proto__Hello__HelloResponse, decodeProto__Hello__HelloRequest, decodeProto__Hello__HelloResponse

@docs defaultProto__Hello__HelloRequest, defaultProto__Hello__HelloResponse, encodeProto__Hello__HelloRequest

@docs encodeProto__Hello__HelloResponse, fieldNumbersProto__Hello__HelloRequest, fieldNumbersProto__Hello__HelloResponse

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Proto__Hello__HelloResponse`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Hello__HelloResponse : { message : Int }
fieldNumbersProto__Hello__HelloResponse =
    { message = 1 }


{-| Default for Proto__Hello__HelloResponse. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Hello__HelloResponse : Proto__Hello__HelloResponse
defaultProto__Hello__HelloResponse =
    { message = "" }


{-| Declares how to decode a `Proto__Hello__HelloResponse` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Hello__HelloResponse : Protobuf.Decode.Decoder Proto__Hello__HelloResponse
decodeProto__Hello__HelloResponse =
    Protobuf.Decode.message
        defaultProto__Hello__HelloResponse
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | message = a }) ]


{-| Declares how to encode a `Proto__Hello__HelloResponse` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Hello__HelloResponse : Proto__Hello__HelloResponse -> Protobuf.Encode.Encoder
encodeProto__Hello__HelloResponse value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.message ) ]


{-| `Proto__Hello__HelloResponse` message

-}
type alias Proto__Hello__HelloResponse =
    { message : String }


{-| The field numbers for the fields of `Proto__Hello__HelloRequest`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersProto__Hello__HelloRequest : { name : Int }
fieldNumbersProto__Hello__HelloRequest =
    { name = 1 }


{-| Default for Proto__Hello__HelloRequest. Should only be used for 'required' decoders as an initial value.

-}
defaultProto__Hello__HelloRequest : Proto__Hello__HelloRequest
defaultProto__Hello__HelloRequest =
    { name = "" }


{-| Declares how to decode a `Proto__Hello__HelloRequest` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeProto__Hello__HelloRequest : Protobuf.Decode.Decoder Proto__Hello__HelloRequest
decodeProto__Hello__HelloRequest =
    Protobuf.Decode.message
        defaultProto__Hello__HelloRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a }) ]


{-| Declares how to encode a `Proto__Hello__HelloRequest` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeProto__Hello__HelloRequest : Proto__Hello__HelloRequest -> Protobuf.Encode.Encoder
encodeProto__Hello__HelloRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.name ) ]


{-| `Proto__Hello__HelloRequest` message

-}
type alias Proto__Hello__HelloRequest =
    { name : String }
