{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Greeter exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 2.3.4
- `protoc` 3.19.4
- the following specification file: `greeter.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.1.0) version 1.2.0 or higher.


-}

import Protobuf.Decode
import Protobuf.Encode


{-| Default for HelloResponse. Should only be used for 'required' decoders as an initial value.


-}
defaultHelloResponse : HelloResponse
defaultHelloResponse =
    { message = "" }


{-| Decode a `HelloResponse` from Bytes


-}
decodeHelloResponse : Protobuf.Decode.Decoder HelloResponse
decodeHelloResponse =
    Protobuf.Decode.message
        defaultHelloResponse
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | message = a }) ]


{-| Encode a `HelloResponse` to Bytes


-}
encodeHelloResponse : HelloResponse -> Protobuf.Encode.Encoder
encodeHelloResponse value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.message ) ]


{-| `HelloResponse` message


-}
type alias HelloResponse =
    { message : String }


{-| Default for HelloRequest. Should only be used for 'required' decoders as an initial value.


-}
defaultHelloRequest : HelloRequest
defaultHelloRequest =
    { name = "" }


{-| Decode a `HelloRequest` from Bytes


-}
decodeHelloRequest : Protobuf.Decode.Decoder HelloRequest
decodeHelloRequest =
    Protobuf.Decode.message
        defaultHelloRequest
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a }) ]


{-| Encode a `HelloRequest` to Bytes


-}
encodeHelloRequest : HelloRequest -> Protobuf.Encode.Encoder
encodeHelloRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.name ) ]


{-| `HelloRequest` message


-}
type alias HelloRequest =
    { name : String }
