{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Greeter exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 1.0.0-beta-2
- `protoc` 3.14.0
- the following specification file: `example/greeter.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.1.0) version 1.1.0 or higher.


-}

import Protobuf.Decode
import Protobuf.Encode


{-| Decode a `HelloResponse` from Bytes


-}
decodeHelloResponse : Protobuf.Decode.Decoder HelloResponse
decodeHelloResponse =
    Protobuf.Decode.message
        { message = "" }
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | message = a }) ]


{-| Encode a `HelloResponse` to Bytes


-}
encodeHelloResponse : HelloResponse -> Protobuf.Encode.Encoder
encodeHelloResponse value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.message ) ]


{-| `HelloResponse` message


-}
type alias HelloResponse =
    { message : String }


{-| Decode a `HelloRequest` from Bytes


-}
decodeHelloRequest : Protobuf.Decode.Decoder HelloRequest
decodeHelloRequest =
    Protobuf.Decode.message
        { name = "" }
        [ Protobuf.Decode.optional 1 Protobuf.Decode.string (\a r -> { r | name = a }) ]


{-| Encode a `HelloRequest` to Bytes


-}
encodeHelloRequest : HelloRequest -> Protobuf.Encode.Encoder
encodeHelloRequest value =
    Protobuf.Encode.message [ ( 1, Protobuf.Encode.string value.name ) ]


{-| `HelloRequest` message


-}
type alias HelloRequest =
    { name : String }
