{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Google.Protobuf.FieldDescriptorProto.Type exposing (Type(..), decodeType, defaultType, encodeType, fieldNumbersType)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.4.4
- `protoc` 3.19.4
- the following specification files: `google/protobuf/descriptor.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version 1.2.0 or higher.

@docs Type, decodeType, defaultType, encodeType, fieldNumbersType

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Type`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersType : Type -> Int
fieldNumbersType n_ =
    case n_ of
        TYPEDOUBLE ->
            1

        TYPEFLOAT ->
            2

        TYPEINT64 ->
            3

        TYPEUINT64 ->
            4

        TYPEINT32 ->
            5

        TYPEFIXED64 ->
            6

        TYPEFIXED32 ->
            7

        TYPEBOOL ->
            8

        TYPESTRING ->
            9

        TYPEGROUP ->
            10

        TYPEMESSAGE ->
            11

        TYPEBYTES ->
            12

        TYPEUINT32 ->
            13

        TYPEENUM ->
            14

        TYPESFIXED32 ->
            15

        TYPESFIXED64 ->
            16

        TYPESINT32 ->
            17

        TYPESINT64 ->
            18


{-| Default for Type. Should only be used for 'required' decoders as an initial value.

-}
defaultType : Type
defaultType =
    TYPEDOUBLE


{-| Declares how to encode a `Type` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeType : Type -> Protobuf.Encode.Encoder
encodeType value =
    Protobuf.Encode.int32 <|
        case value of
            TYPEDOUBLE ->
                1

            TYPEFLOAT ->
                2

            TYPEINT64 ->
                3

            TYPEUINT64 ->
                4

            TYPEINT32 ->
                5

            TYPEFIXED64 ->
                6

            TYPEFIXED32 ->
                7

            TYPEBOOL ->
                8

            TYPESTRING ->
                9

            TYPEGROUP ->
                10

            TYPEMESSAGE ->
                11

            TYPEBYTES ->
                12

            TYPEUINT32 ->
                13

            TYPEENUM ->
                14

            TYPESFIXED32 ->
                15

            TYPESFIXED64 ->
                16

            TYPESINT32 ->
                17

            TYPESINT64 ->
                18


{-| Declares how to decode a `Type` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeType : Protobuf.Decode.Decoder Type
decodeType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    1 ->
                        TYPEDOUBLE

                    2 ->
                        TYPEFLOAT

                    3 ->
                        TYPEINT64

                    4 ->
                        TYPEUINT64

                    5 ->
                        TYPEINT32

                    6 ->
                        TYPEFIXED64

                    7 ->
                        TYPEFIXED32

                    8 ->
                        TYPEBOOL

                    9 ->
                        TYPESTRING

                    10 ->
                        TYPEGROUP

                    11 ->
                        TYPEMESSAGE

                    12 ->
                        TYPEBYTES

                    13 ->
                        TYPEUINT32

                    14 ->
                        TYPEENUM

                    15 ->
                        TYPESFIXED32

                    16 ->
                        TYPESFIXED64

                    17 ->
                        TYPESINT32

                    18 ->
                        TYPESINT64

                    _ ->
                        TYPEDOUBLE
            )


{-| `Type` enumeration

-}
type Type
    = TYPEDOUBLE
    | TYPEFLOAT
    | TYPEINT64
    | TYPEUINT64
    | TYPEINT32
    | TYPEFIXED64
    | TYPEFIXED32
    | TYPEBOOL
    | TYPESTRING
    | TYPEGROUP
    | TYPEMESSAGE
    | TYPEBYTES
    | TYPEUINT32
    | TYPEENUM
    | TYPESFIXED32
    | TYPESFIXED64
    | TYPESINT32
    | TYPESINT64
