{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Google.Protobuf exposing (..)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 3.0.0-beta.1
- `protoc` 3.19.4
- the following specification files: `google/protobuf/descriptor.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version 1.2.0 or higher.


-}

import Proto.Google.Protobuf.Internals_
import Protobuf.Decode
import Protobuf.Encode


{-| Default for GeneratedCodeInfo. Should only be used for 'required' decoders as an initial value.


-}
defaultGeneratedCodeInfo : GeneratedCodeInfo
defaultGeneratedCodeInfo =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__GeneratedCodeInfo


{-| Declares how to decode a `GeneratedCodeInfo` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeGeneratedCodeInfo : Protobuf.Decode.Decoder GeneratedCodeInfo
decodeGeneratedCodeInfo =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__GeneratedCodeInfo


{-| Declares how to encode a `GeneratedCodeInfo` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeGeneratedCodeInfo : GeneratedCodeInfo -> Protobuf.Encode.Encoder
encodeGeneratedCodeInfo =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__GeneratedCodeInfo


{-| `GeneratedCodeInfo` message


-}
type alias GeneratedCodeInfo =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__GeneratedCodeInfo


{-| Default for SourceCodeInfo. Should only be used for 'required' decoders as an initial value.


-}
defaultSourceCodeInfo : SourceCodeInfo
defaultSourceCodeInfo =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__SourceCodeInfo


{-| Declares how to decode a `SourceCodeInfo` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeSourceCodeInfo : Protobuf.Decode.Decoder SourceCodeInfo
decodeSourceCodeInfo =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__SourceCodeInfo


{-| Declares how to encode a `SourceCodeInfo` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeSourceCodeInfo : SourceCodeInfo -> Protobuf.Encode.Encoder
encodeSourceCodeInfo =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__SourceCodeInfo


{-| `SourceCodeInfo` message


-}
type alias SourceCodeInfo =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__SourceCodeInfo


{-| Default for UninterpretedOption. Should only be used for 'required' decoders as an initial value.


-}
defaultUninterpretedOption : UninterpretedOption
defaultUninterpretedOption =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__UninterpretedOption


{-| Declares how to decode a `UninterpretedOption` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeUninterpretedOption : Protobuf.Decode.Decoder UninterpretedOption
decodeUninterpretedOption =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__UninterpretedOption


{-| Declares how to encode a `UninterpretedOption` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeUninterpretedOption : UninterpretedOption -> Protobuf.Encode.Encoder
encodeUninterpretedOption =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__UninterpretedOption


{-| `UninterpretedOption` message


-}
type alias UninterpretedOption =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__UninterpretedOption


{-| Default for MethodOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultMethodOptions : MethodOptions
defaultMethodOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__MethodOptions


{-| Declares how to decode a `MethodOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeMethodOptions : Protobuf.Decode.Decoder MethodOptions
decodeMethodOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__MethodOptions


{-| Declares how to encode a `MethodOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeMethodOptions : MethodOptions -> Protobuf.Encode.Encoder
encodeMethodOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__MethodOptions


{-| `MethodOptions` message


-}
type alias MethodOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__MethodOptions


{-| Default for ServiceOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultServiceOptions : ServiceOptions
defaultServiceOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__ServiceOptions


{-| Declares how to decode a `ServiceOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeServiceOptions : Protobuf.Decode.Decoder ServiceOptions
decodeServiceOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__ServiceOptions


{-| Declares how to encode a `ServiceOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeServiceOptions : ServiceOptions -> Protobuf.Encode.Encoder
encodeServiceOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__ServiceOptions


{-| `ServiceOptions` message


-}
type alias ServiceOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ServiceOptions


{-| Default for EnumValueOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumValueOptions : EnumValueOptions
defaultEnumValueOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumValueOptions


{-| Declares how to decode a `EnumValueOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumValueOptions : Protobuf.Decode.Decoder EnumValueOptions
decodeEnumValueOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumValueOptions


{-| Declares how to encode a `EnumValueOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumValueOptions : EnumValueOptions -> Protobuf.Encode.Encoder
encodeEnumValueOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumValueOptions


{-| `EnumValueOptions` message


-}
type alias EnumValueOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumValueOptions


{-| Default for EnumOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumOptions : EnumOptions
defaultEnumOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumOptions


{-| Declares how to decode a `EnumOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumOptions : Protobuf.Decode.Decoder EnumOptions
decodeEnumOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumOptions


{-| Declares how to encode a `EnumOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumOptions : EnumOptions -> Protobuf.Encode.Encoder
encodeEnumOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumOptions


{-| `EnumOptions` message


-}
type alias EnumOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumOptions


{-| Default for OneofOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultOneofOptions : OneofOptions
defaultOneofOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__OneofOptions


{-| Declares how to decode a `OneofOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeOneofOptions : Protobuf.Decode.Decoder OneofOptions
decodeOneofOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__OneofOptions


{-| Declares how to encode a `OneofOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeOneofOptions : OneofOptions -> Protobuf.Encode.Encoder
encodeOneofOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__OneofOptions


{-| `OneofOptions` message


-}
type alias OneofOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__OneofOptions


{-| Default for FieldOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultFieldOptions : FieldOptions
defaultFieldOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FieldOptions


{-| Declares how to decode a `FieldOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFieldOptions : Protobuf.Decode.Decoder FieldOptions
decodeFieldOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FieldOptions


{-| Declares how to encode a `FieldOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFieldOptions : FieldOptions -> Protobuf.Encode.Encoder
encodeFieldOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FieldOptions


{-| `FieldOptions` message


-}
type alias FieldOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FieldOptions


{-| Default for MessageOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultMessageOptions : MessageOptions
defaultMessageOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__MessageOptions


{-| Declares how to decode a `MessageOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeMessageOptions : Protobuf.Decode.Decoder MessageOptions
decodeMessageOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__MessageOptions


{-| Declares how to encode a `MessageOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeMessageOptions : MessageOptions -> Protobuf.Encode.Encoder
encodeMessageOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__MessageOptions


{-| `MessageOptions` message


-}
type alias MessageOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__MessageOptions


{-| Default for FileOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultFileOptions : FileOptions
defaultFileOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FileOptions


{-| Declares how to decode a `FileOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFileOptions : Protobuf.Decode.Decoder FileOptions
decodeFileOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FileOptions


{-| Declares how to encode a `FileOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFileOptions : FileOptions -> Protobuf.Encode.Encoder
encodeFileOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FileOptions


{-| `FileOptions` message


-}
type alias FileOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FileOptions


{-| Default for MethodDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultMethodDescriptorProto : MethodDescriptorProto
defaultMethodDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__MethodDescriptorProto


{-| Declares how to decode a `MethodDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeMethodDescriptorProto : Protobuf.Decode.Decoder MethodDescriptorProto
decodeMethodDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__MethodDescriptorProto


{-| Declares how to encode a `MethodDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeMethodDescriptorProto : MethodDescriptorProto -> Protobuf.Encode.Encoder
encodeMethodDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__MethodDescriptorProto


{-| `MethodDescriptorProto` message


-}
type alias MethodDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__MethodDescriptorProto


{-| Default for ServiceDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultServiceDescriptorProto : ServiceDescriptorProto
defaultServiceDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__ServiceDescriptorProto


{-| Declares how to decode a `ServiceDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeServiceDescriptorProto : Protobuf.Decode.Decoder ServiceDescriptorProto
decodeServiceDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__ServiceDescriptorProto


{-| Declares how to encode a `ServiceDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeServiceDescriptorProto : ServiceDescriptorProto -> Protobuf.Encode.Encoder
encodeServiceDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__ServiceDescriptorProto


{-| `ServiceDescriptorProto` message


-}
type alias ServiceDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ServiceDescriptorProto


{-| Default for EnumValueDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumValueDescriptorProto : EnumValueDescriptorProto
defaultEnumValueDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumValueDescriptorProto


{-| Declares how to decode a `EnumValueDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumValueDescriptorProto : Protobuf.Decode.Decoder EnumValueDescriptorProto
decodeEnumValueDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumValueDescriptorProto


{-| Declares how to encode a `EnumValueDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumValueDescriptorProto : EnumValueDescriptorProto -> Protobuf.Encode.Encoder
encodeEnumValueDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumValueDescriptorProto


{-| `EnumValueDescriptorProto` message


-}
type alias EnumValueDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumValueDescriptorProto


{-| Default for EnumDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultEnumDescriptorProto : EnumDescriptorProto
defaultEnumDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__EnumDescriptorProto


{-| Declares how to decode a `EnumDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeEnumDescriptorProto : Protobuf.Decode.Decoder EnumDescriptorProto
decodeEnumDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__EnumDescriptorProto


{-| Declares how to encode a `EnumDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeEnumDescriptorProto : EnumDescriptorProto -> Protobuf.Encode.Encoder
encodeEnumDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__EnumDescriptorProto


{-| `EnumDescriptorProto` message


-}
type alias EnumDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__EnumDescriptorProto


{-| Default for OneofDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultOneofDescriptorProto : OneofDescriptorProto
defaultOneofDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__OneofDescriptorProto


{-| Declares how to decode a `OneofDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeOneofDescriptorProto : Protobuf.Decode.Decoder OneofDescriptorProto
decodeOneofDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__OneofDescriptorProto


{-| Declares how to encode a `OneofDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeOneofDescriptorProto : OneofDescriptorProto -> Protobuf.Encode.Encoder
encodeOneofDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__OneofDescriptorProto


{-| `OneofDescriptorProto` message


-}
type alias OneofDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__OneofDescriptorProto


{-| Default for FieldDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultFieldDescriptorProto : FieldDescriptorProto
defaultFieldDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FieldDescriptorProto


{-| Declares how to decode a `FieldDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFieldDescriptorProto : Protobuf.Decode.Decoder FieldDescriptorProto
decodeFieldDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FieldDescriptorProto


{-| Declares how to encode a `FieldDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFieldDescriptorProto : FieldDescriptorProto -> Protobuf.Encode.Encoder
encodeFieldDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FieldDescriptorProto


{-| `FieldDescriptorProto` message


-}
type alias FieldDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FieldDescriptorProto


{-| Default for ExtensionRangeOptions. Should only be used for 'required' decoders as an initial value.


-}
defaultExtensionRangeOptions : ExtensionRangeOptions
defaultExtensionRangeOptions =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__ExtensionRangeOptions


{-| Declares how to decode a `ExtensionRangeOptions` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeExtensionRangeOptions : Protobuf.Decode.Decoder ExtensionRangeOptions
decodeExtensionRangeOptions =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__ExtensionRangeOptions


{-| Declares how to encode a `ExtensionRangeOptions` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeExtensionRangeOptions : ExtensionRangeOptions -> Protobuf.Encode.Encoder
encodeExtensionRangeOptions =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__ExtensionRangeOptions


{-| `ExtensionRangeOptions` message


-}
type alias ExtensionRangeOptions =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__ExtensionRangeOptions


{-| Unwrap a `DescriptorProto` from its wrapper `DescriptorProto_.`


-}
unwrapDescriptorProto : DescriptorProto_ -> DescriptorProto
unwrapDescriptorProto =
    Proto.Google.Protobuf.Internals_.unwrapProto__Google__Protobuf__DescriptorProto


{-| Wrap a `DescriptorProto` into its wrapper `DescriptorProto_.`


-}
wrapDescriptorProto : DescriptorProto -> DescriptorProto_
wrapDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__DescriptorProto_


{-| Type wrapper for alias type `DescriptorProto` to avoid unlimited recursion.


For a more in-depth explanation why we need this, read this: https://github.com/elm/compiler/blob/master/hints/recursive-alias.md.


-}
type alias DescriptorProto_ =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__DescriptorProto_


{-| Default for DescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultDescriptorProto : DescriptorProto
defaultDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__DescriptorProto


{-| Declares how to decode a `DescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeDescriptorProto : Protobuf.Decode.Decoder DescriptorProto
decodeDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__DescriptorProto


{-| Declares how to encode a `DescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeDescriptorProto : DescriptorProto -> Protobuf.Encode.Encoder
encodeDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__DescriptorProto


{-| `DescriptorProto` message


-}
type alias DescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__DescriptorProto


{-| Default for FileDescriptorProto. Should only be used for 'required' decoders as an initial value.


-}
defaultFileDescriptorProto : FileDescriptorProto
defaultFileDescriptorProto =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FileDescriptorProto


{-| Declares how to decode a `FileDescriptorProto` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFileDescriptorProto : Protobuf.Decode.Decoder FileDescriptorProto
decodeFileDescriptorProto =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FileDescriptorProto


{-| Declares how to encode a `FileDescriptorProto` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFileDescriptorProto : FileDescriptorProto -> Protobuf.Encode.Encoder
encodeFileDescriptorProto =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FileDescriptorProto


{-| `FileDescriptorProto` message


-}
type alias FileDescriptorProto =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FileDescriptorProto


{-| Default for FileDescriptorSet. Should only be used for 'required' decoders as an initial value.


-}
defaultFileDescriptorSet : FileDescriptorSet
defaultFileDescriptorSet =
    Proto.Google.Protobuf.Internals_.defaultProto__Google__Protobuf__FileDescriptorSet


{-| Declares how to decode a `FileDescriptorSet` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.


-}
decodeFileDescriptorSet : Protobuf.Decode.Decoder FileDescriptorSet
decodeFileDescriptorSet =
    Proto.Google.Protobuf.Internals_.decodeProto__Google__Protobuf__FileDescriptorSet


{-| Declares how to encode a `FileDescriptorSet` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.


-}
encodeFileDescriptorSet : FileDescriptorSet -> Protobuf.Encode.Encoder
encodeFileDescriptorSet =
    Proto.Google.Protobuf.Internals_.encodeProto__Google__Protobuf__FileDescriptorSet


{-| `FileDescriptorSet` message


-}
type alias FileDescriptorSet =
    Proto.Google.Protobuf.Internals_.Proto__Google__Protobuf__FileDescriptorSet
