name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
          registry-url: https://registry.npmjs.org
      - uses: justgook/setup-elm@1.2.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - uses: arduino/setup-protoc@v1.1.2
        with:
          version: 3.14.0
      - name: install
        run: npm ci
      - name: build
        run: |
          which protoc
          protoc --version
          
          mkdir generated
          npm ci
          npm run build
      - name: test
        run: npm test
      - name: npm publish
        if: ${{ github.event_name == 'push' }}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish --access public || true
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: generated
          path: generated/Proto
